version: '3.5'
services:      
  oracle-db:
    build:
      context: .
      shm_size: 1g #when building
    ports:
      - "7521:1521"
      - "7580:8080"
    image: ea/oracle:1
    container_name: ea.oracle
    shm_size: '1gb' #when running                  
    #volumes:
      #- ./docker-oracle-fs/data:/u01/app/oracle/oradata
      #- ./releases/1.3.0/db/consolidated/oracle:/u01/app/oracle/scripts/startup
        